# POST http://localhost:5000/category
# GET http://localhost:5000/test

# POST http://localhost:5000
PUT http://localhost:5000/contact/1
Content-Type: application/json

{
    "email":"lenain@gmail.com",
    "firstname":"billy"
}
